---
title: Wiki
timezone: Asia/Jakarta
collections:
  docs:
    title: Documentation
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: docs
  values:
    seo:
      type: Article
    _comments:
      category: Group navigation links with this field
      order: Used to sort links in the navigation
- scope:
    path: ''
    type: posts
  values:
    _comments:
      type: Marks the impact of this release
url: https://long-pig.cloudvent.net
baseurl: 
google_analytics_key: 
show_full_navigation: true
logo: "/siteicon.png"
description: Sebuah dokumentasi keberhasilan.
author:
  name: 
  email: 
  twitter: 
social:
  name: Wikih
  links:
  - http://kitamasih.tk
permalink: pretty
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
types:
- minor
- major
